chore: Try coverage with .txt format

diff --git a/.github/workflows/chores.yml b/.github/workflows/chores.yml
--- a/.github/workflows/chores.yml
+++ b/.github/workflows/chores.yml
@@ -132,13 +132,13 @@ jobs:
         run: |
           go mod vendor
           go mod tidy
-          CGO_ENABLED=0 go test -coverprofile=coverage.out -mod=vendor -v -count=1 ./...
+          CGO_ENABLED=0 go test -coverprofile=coverage.txt -mod=vendor -v -count=1 ./...
 
       - name: Archive code coverage results
         uses: actions/upload-artifact@v4
         with:
           name: code-coverage
-          path: coverage.out
+          path: coverage.txt
 
   report-coverage:
     name: Report code coverage
@@ -164,7 +164,7 @@ jobs:
           path: .github/outputs
 
       - name: Rename code coverage results file from current run
-        run: mv .github/outputs/coverage.out .github/outputs/new-coverage.out
+        run: mv .github/outputs/coverage.txt .github/outputs/new-coverage.txt
 
       - name: Find and download last successful coverage artifact on main
         id: get_baseline
@@ -193,10 +193,10 @@ jobs:
           gh run download $RUN_ID --name=code-coverage --dir=.github/outputs
 
           # Rename the file to match expected format
-          if [[ -f ".github/outputs/coverage.out" ]]; then
-            mv .github/outputs/coverage.out .github/outputs/old-coverage.out
+          if [[ -f ".github/outputs/coverage.txt" ]]; then
+            mv .github/outputs/coverage.txt .github/outputs/old-coverage.txt
           else
-            echo "Error: coverage.out not found in downloaded artifacts."
+            echo "Error: coverage.txt not found in downloaded artifacts."
             exit 1
           fi
 
@@ -209,8 +209,8 @@ jobs:
       - name: Compare code coverage results
         run: |
           go-coverage-report \
-            .github/outputs/old-coverage.out \
-            .github/outputs/new-coverage.out \
+            .github/outputs/old-coverage.txt \
+            .github/outputs/new-coverage.txt \
             .github/outputs/all_changed_files.json \
           > .github/outputs/coverage-comment.md
 
@@ -226,123 +226,123 @@ jobs:
 
           gh pr comment ${{ github.event.number }} --body-file=.github/outputs/coverage-comment.md
 
-  coverage-badge:
-    name: Update coverage badge on README
-    runs-on: ubuntu-latest
-    needs: [ test ]
-    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v4
+#  coverage-badge:
+#    name: Update coverage badge on README
+#    runs-on: ubuntu-latest
+#    needs: [ test ]
+#    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
+#    steps:
+#      - name: Checkout repository
+#        uses: actions/checkout@v4
+#
+#      - name: Download coverage artifact
+#        uses: actions/download-artifact@v4
+#        with:
+#          name: code-coverage
+#          path: .
+#
+#      - name: List downloaded files (debugging)
+#        run: ls -R
+#
+#      - name: Verify README exists
+#        run: ls -l README.md || echo "README.md not found!"
+#
+#      - name: Generate Go Coverage Badge
+#        id: generate-badge
+#        uses: tj-actions/coverage-badge-go@v2
+#        with:
+#          filename: coverage.out
+#
+#      - name: Verify Changed README
+#        if: steps.generate-badge.outcome == 'success'
+#        id: verify-changed-readme
+#        run: |
+#          git fetch origin main
+#          if git diff --quiet origin/main -- README.md; then
+#            echo "README.md has NOT changed."
+#            echo "readme_changed=false" >> $GITHUB_ENV
+#          else
+#            echo "README.md has changed."
+#            echo "readme_changed=true" >> $GITHUB_ENV
+#          fi
+#
+#      - name: Commit changes
+#        if: env.readme_changed == 'true'
+#        env:
+#          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+#        run: |
+#          # Ensure we are on the main branch
+#          git fetch origin main
+#          git checkout main
+#          git pull origin main
+#
+#          # Configure Git
+#          git config --local user.email "action@github.com"
+#          git config --local user.name "GitHub Action"
+#
+#          # Commit and push changes
+#          git add README.md
+#          git commit -m "chore: Updated coverage badge." || echo "No changes to commit"
+#          git push origin main
 
-      - name: Download coverage artifact
-        uses: actions/download-artifact@v4
-        with:
-          name: code-coverage
-          path: .
-
-      - name: List downloaded files (debugging)
-        run: ls -R
-
-      - name: Verify README exists
-        run: ls -l README.md || echo "README.md not found!"
-
-      - name: Generate Go Coverage Badge
-        id: generate-badge
-        uses: tj-actions/coverage-badge-go@v2
-        with:
-          filename: coverage.out
-
-      - name: Verify Changed README
-        if: steps.generate-badge.outcome == 'success'
-        id: verify-changed-readme
-        run: |
-          git fetch origin main
-          if git diff --quiet origin/main -- README.md; then
-            echo "README.md has NOT changed."
-            echo "readme_changed=false" >> $GITHUB_ENV
-          else
-            echo "README.md has changed."
-            echo "readme_changed=true" >> $GITHUB_ENV
-          fi
-
-      - name: Commit changes
-        if: env.readme_changed == 'true'
-        env:
-          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        run: |
-          # Ensure we are on the main branch
-          git fetch origin main
-          git checkout main
-          git pull origin main
-
-          # Configure Git
-          git config --local user.email "action@github.com"
-          git config --local user.name "GitHub Action"
-
-          # Commit and push changes
-          git add README.md
-          git commit -m "chore: Updated coverage badge." || echo "No changes to commit"
-          git push origin main
-
-  capture-coverage:
-    name: Capture coverage in platform_health repo
-    runs-on: ubuntu-latest
-    needs: [test]
-    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
-    steps:
-      - name: Configure git for private modules
-        run: git config --global url."https://user:${TOKEN}@github.com".insteadOf "https://github.com"
-
-      - name: Clone the code
-        uses: actions/checkout@v4
-
-      - name: Setup Go
-        uses: actions/setup-go@v5
-        with:
-          go-version-file: go.mod
-
-      - name: Download coverage artifact
-        uses: actions/download-artifact@v4
-        with:
-          name: code-coverage
-          path: .
-
-      - name: Capture coverage in health repo
-        run: |
-          go install github.com/axw/gocov/gocov@latest
-          gocov convert coverage.out | gocov report > coverage-mdai-event-hub.txt
-
-      - name: Generate a token
-        id: generate-token
-        uses: actions/create-github-app-token@v1
-        with:
-          app-id: ${{ vars.PLATFORM_HEALTH_ACCESS_APP_ID }}
-          private-key: ${{ secrets.APP_PRIVATE_KEY }}
-
-      - name: Set safe git directory
-        env:
-          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
-        run: git config --global --add safe.directory '*'
-      - name: Commit coverage to health repo
-        env:
-          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
-        run: |
-          git clone https://x-access-token:${GH_TOKEN}@github.com/decisiveai/platform-health.git
-          cd platform-health
-          
-          # Configure git
-          git config --global user.email "action@github.com"
-          git config --global user.name "GitHub Action"
-          
-          # Copy the new coverage file
-          cp ../coverage-mdai-event-hub.txt .
-          
-          # Commit and push changes
-          git add coverage-mdai-event-hub.txt
-          if git diff --cached --quiet; then
-            echo "✅ No changes to commit."
-            exit 0
-          fi
-          git commit -m "chore: Update coverage report from CI"
-          git push origin main
+#  capture-coverage:
+#    name: Capture coverage in platform_health repo
+#    runs-on: ubuntu-latest
+#    needs: [test]
+#    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
+#    steps:
+#      - name: Configure git for private modules
+#        run: git config --global url."https://user:${TOKEN}@github.com".insteadOf "https://github.com"
+#
+#      - name: Clone the code
+#        uses: actions/checkout@v4
+#
+#      - name: Setup Go
+#        uses: actions/setup-go@v5
+#        with:
+#          go-version-file: go.mod
+#
+#      - name: Download coverage artifact
+#        uses: actions/download-artifact@v4
+#        with:
+#          name: code-coverage
+#          path: .
+#
+#      - name: Capture coverage in health repo
+#        run: |
+#          go install github.com/axw/gocov/gocov@latest
+#          gocov convert coverage.out | gocov report > coverage-mdai-event-hub.txt
+#
+#      - name: Generate a token
+#        id: generate-token
+#        uses: actions/create-github-app-token@v1
+#        with:
+#          app-id: ${{ vars.PLATFORM_HEALTH_ACCESS_APP_ID }}
+#          private-key: ${{ secrets.APP_PRIVATE_KEY }}
+#
+#      - name: Set safe git directory
+#        env:
+#          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
+#        run: git config --global --add safe.directory '*'
+#      - name: Commit coverage to health repo
+#        env:
+#          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
+#        run: |
+#          git clone https://x-access-token:${GH_TOKEN}@github.com/decisiveai/platform-health.git
+#          cd platform-health
+#
+#          # Configure git
+#          git config --global user.email "action@github.com"
+#          git config --global user.name "GitHub Action"
+#
+#          # Copy the new coverage file
+#          cp ../coverage-mdai-event-hub.txt .
+#
+#          # Commit and push changes
+#          git add coverage-mdai-event-hub.txt
+#          if git diff --cached --quiet; then
+#            echo "✅ No changes to commit."
+#            exit 0
+#          fi
+#          git commit -m "chore: Update coverage report from CI"
+#          git push origin main
